[package]
name = "poost-server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
poost-core.workspace = true
axum = "0.8.7"
tower-http = { version = "0.6.8", features = ["cors", "trace", "limit"] }
anyhow.workspace = true