[package]
name = "guest-loader"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
bytes = "1.5"
futures = "0.3"
minisign-verify = "0.2"
reqwest = { version = "0.12", features = ["json", "stream"] }
serde = { workspace = true, features = ["derive"] }
thiserror = "1.0"
tokio = { workspace = true, features = ["fs", "io-util", "macros", "rt-multi-thread"] }
zkboost-server-config = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
tempfile = "3.2"
